misc/weather: Fixes for python3+

diff --git a/misc/weather/weather.SlackBuild b/misc/weather/weather.SlackBuild
--- a/misc/weather/weather.SlackBuild
+++ b/misc/weather/weather.SlackBuild
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Slackware build script for weather
 #
@@ -8,69 +8,73 @@
 #
 # * Updated to version 2.3 20200319
 #
+# * Python 3 site-packages path, noarch, template cleanup 20261004
+#
 
+cd $(dirname $0) ; CWD=$(pwd)
 
 PRGNAM=weather
 VERSION=${VERSION:-2.5.0}
-BUILD=${BUILD:-1}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_SBo}
+PKGTYPE=${PKGTYPE:-tgz}
+ARCH=noarch
 
-if [ -z "$ARCH" ]; then
-  case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
-    arm*) ARCH=arm ;;
-       *) ARCH=$( uname -m ) ;;
-  esac
+if [ ! -z "${PRINT_PACKAGE_NAME:-}" ]; then
+  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
+  exit 0
 fi
 
-CWD=$(pwd)
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "x86_64" ]; then
-  LIBDIRSUFFIX="64"
-else
-  LIBDIRSUFFIX=""
-fi
+set -eu
+umask 022
 
-set -e
+PYSITE=$(python3 -c 'import sysconfig; print(sysconfig.get_path("purelib"))')
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
+rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
 cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
- -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
+# Pin the interpreter, as upstream suggests for distributions
+sed -i '1s|^#!.*|#!/usr/bin/python3|' weather
+
+# Slackware's expect package ships /usr/bin/weather; see README
 mkdir -p $PKG/usr/bin
-cp -a weather $PKG/usr/bin/weather.weather
+install -m 0755 weather $PKG/usr/bin/weather.weather
 ( cd $PKG/usr/bin ; ln -s weather.weather weather )
 
+# cachedir already defaults to ~/.weather; upstream weatherrc has only [default]
 mkdir -p $PKG/etc
 cat << EOF >> weatherrc
-cachedir = ~/.weather
 setpath = /usr/share/weather-util
 EOF
 cp -a weatherrc $PKG/etc/weatherrc.new
 
 mkdir -p $PKG/usr/share/weather-util
-cp -a {airports,places,stations,zctas,zones} $PKG/usr/share/weather-util
+cp -a airports places stations zctas zones $PKG/usr/share/weather-util
 
 mkdir -p $PKG/usr/man/man{1,5}
 gzip -9c weather.1 > $PKG/usr/man/man1/weather.1.gz
 gzip -9c weatherrc.5 > $PKG/usr/man/man5/weatherrc.5.gz
 
-mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/python2.7/site-packages
-cp -a weather.py $PKG/usr/lib${LIBDIRSUFFIX}/python2.7/site-packages
+mkdir -p $PKG$PYSITE
+cp -a weather.py $PKG$PYSITE
+python3 -m compileall -q -d $PYSITE $PKG$PYSITE
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a FAQ INSTALL LICENSE README $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a FAQ INSTALL LICENSE NEWS README $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
@@ -78,4 +82,4 @@ cat $CWD/slack-desc > $PKG/install/slack-desc
 cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
